# List Albums
GET http://localhost:8080/albums

###
# Create Album
POST http://localhost:8080/albums
Content-Type: application/json

{
    "title": "The New Modern Sound of Betty Carter",
    "artist": "Betty Carter",
    "price": -1
}

###
# Get Album by ID
GET http://localhost:8080/albums/10

###
# Update album
PUT http://localhost:8080/albums/4
Content-Type: application/json

{
    "title": "Novo nome"
}
