// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/gin-gonic/gin"
	"github.com/google/wire"
	"github.com/swaggo/files"
	"github.com/swaggo/gin-swagger"
	"go-api/controllers"
	"go-api/domain/dtos"
	"go-api/domain/repositories"
	"go-api/infra/config/env"
	postgres2 "go-api/infra/config/postgres"
	"go-api/infra/middlewares"
	"go-api/infra/mocks"
	"go-api/infra/repositories/memory"
	"go-api/infra/repositories/postgres"
	"go-api/infra/security"
	"go-api/usecases"
	"gorm.io/gorm"
)

import (
	_ "go-api/docs"
)

// Injectors from wire-config.go:

func InitializeServer() *gin.Engine {
	postgresAlbumRepository := postgres.NewPostgresRepository()
	getAlbumsUsecase := usecases.NewGetAlbumsUsecase(postgresAlbumRepository)
	getAllAlbumsController := controllers.NewGetAllAlbumsController(getAlbumsUsecase)
	createAlbumUsecase := usecases.NewCreateAlbumUsecase(postgresAlbumRepository)
	createAlbumController := controllers.NewCreateAlbumController(createAlbumUsecase)
	getAlbumByIDUsecase := usecases.NewGetAlbumByIdUsecase(postgresAlbumRepository)
	getAlbumByIdController := controllers.NewGetAlbumByIDController(getAlbumByIDUsecase)
	updateAlbumUsecase := usecases.NewUpdateAlbumUsecase(postgresAlbumRepository)
	updateAlbumController := controllers.NewUpdateAlbumController(updateAlbumUsecase)
	string2 := provideJWTSecret()
	tokenService := security.NewJwtService(string2)
	engine := newServer(getAllAlbumsController, createAlbumController, getAlbumByIdController, updateAlbumController, tokenService)
	return engine
}

// wire-config.go:

func provideJWTSecret() string {
	env2 := env.LoadEnv()
	return env2.JwtSecret
}

var securitySet = wire.NewSet(
	provideJWTSecret, security.NewJwtService,
)

var albumRepositorySet = wire.NewSet(memory.NewAlbumRepository, mocks.GetAlbumsInMemory, wire.Bind(new(repositories.AlbumRepository), new(*memory.InMemoryAlbumRepository)))

func provideDbInstance() *gorm.DB {
	DB := postgres2.DB
	return DB
}

var postgresRepositorySet = wire.NewSet(postgres.NewPostgresRepository, provideDbInstance, wire.Bind(new(repositories.AlbumRepository), new(*postgres.PostgresAlbumRepository)))

var usecasesSet = wire.NewSet(usecases.NewGetAlbumsUsecase, usecases.NewCreateAlbumUsecase, usecases.NewGetAlbumByIdUsecase, usecases.NewUpdateAlbumUsecase)

var controllersSet = wire.NewSet(controllers.NewGetAllAlbumsController, controllers.NewCreateAlbumController, controllers.NewGetAlbumByIDController, controllers.NewUpdateAlbumController)

func newServer(
	getAllAlbumsController *controllers.GetAllAlbumsController,
	createAlbumController *controllers.CreateAlbumController,
	getAlbumByIdController *controllers.GetAlbumByIdController,
	updateAlbumController *controllers.UpdateAlbumController,
	tokenService security.TokenService,
) *gin.Engine {
	router := gin.Default()

	router.GET("/swagger/*any", ginSwagger.WrapHandler(swaggerFiles.Handler))

	router.GET("/albums", getAllAlbumsController.Handle)
	router.GET("/albums/:id", getAlbumByIdController.Handle)
	router.POST("/albums", middlewares.ValidateBody[dtos.CreateAlbumDto](), createAlbumController.Handle)
	router.PUT("/albums/:id", middlewares.ValidateBody[dtos.UpdateAlbumDto](), updateAlbumController.Handle)

	return router
}
