// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package config

import (
	"github.com/gin-gonic/gin"
	"github.com/google/wire"
	"github.com/swaggo/files"
	"github.com/swaggo/gin-swagger"
	"go-api/controllers"
	"go-api/domain/dtos"
	"go-api/domain/repositories"
	"go-api/infra/middlewares"
	"go-api/infra/mocks"
	"go-api/infra/repositories"
	"go-api/infra/security"
	"go-api/usecases"
)

import (
	_ "go-api/docs"
)

// Injectors from wire.go:

func InitializeServer() *gin.Engine {
	v := mocks.GetAlbumsInMemory()
	albumRepositoryMemory := inmemorydb.NewAlbumRepository(v)
	getAlbumsUsecase := usecases.NewGetAlbumsUsecase(albumRepositoryMemory)
	getAllAlbumsController := controllers.NewGetAllAlbumsController(getAlbumsUsecase)
	createAlbumUsecase := usecases.NewCreateAlbumUsecase(albumRepositoryMemory)
	createAlbumController := controllers.NewCreateAlbumController(createAlbumUsecase)
	getAlbumByIDUsecase := usecases.NewGetAlbumByIdUsecase(albumRepositoryMemory)
	getAlbumByIdController := controllers.NewGetAlbumByIDController(getAlbumByIDUsecase)
	updateAlbumUsecase := usecases.NewUpdateAlbumUsecase(albumRepositoryMemory)
	updateAlbumController := controllers.NewUpdateAlbumController(updateAlbumUsecase)
	string2 := provideJWTSecret()
	tokenService := security.NewJwtService(string2)
	engine := newServer(getAllAlbumsController, createAlbumController, getAlbumByIdController, updateAlbumController, tokenService)
	return engine
}

// wire.go:

func provideJWTSecret() string {
	env := LoadEnv()
	return env.JwtSecret
}

var securitySet = wire.NewSet(
	provideJWTSecret, security.NewJwtService,
)

var albumRepositorySet = wire.NewSet(inmemorydb.NewAlbumRepository, mocks.GetAlbumsInMemory, wire.Bind(new(repositories.AlbumRepository), new(*inmemorydb.AlbumRepositoryMemory)))

var usecasesSet = wire.NewSet(usecases.NewGetAlbumsUsecase, usecases.NewCreateAlbumUsecase, usecases.NewGetAlbumByIdUsecase, usecases.NewUpdateAlbumUsecase)

var controllersSet = wire.NewSet(controllers.NewGetAllAlbumsController, controllers.NewCreateAlbumController, controllers.NewGetAlbumByIDController, controllers.NewUpdateAlbumController)

func newServer(
	getAllAlbumsController *controllers.GetAllAlbumsController,
	createAlbumController *controllers.CreateAlbumController,
	getAlbumByIdController *controllers.GetAlbumByIdController,
	updateAlbumController *controllers.UpdateAlbumController,
	tokenService security.TokenService,
) *gin.Engine {
	router := gin.Default()

	router.GET("/swagger/*any", ginSwagger.WrapHandler(swaggerFiles.Handler))

	router.GET("/albums", getAllAlbumsController.Handle)
	router.GET("/albums/:id", getAlbumByIdController.Handle)
	router.POST("/albums", middlewares.ValidateBody[dtos.CreateAlbumDto](), createAlbumController.Handle)
	router.PUT("/albums/:id", middlewares.ValidateBody[dtos.UpdateAlbumDto](), updateAlbumController.Handle)

	return router
}
