// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/albums": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Álbuns"
                ],
                "summary": "Lista os álbuns cadastrados",
                "responses": {
                    "200": {
                        "description": "Lista de álbuns",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/entities.Album"
                            }
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "tags": [
                    "Álbuns"
                ],
                "summary": "Cria um novo álbum",
                "parameters": [
                    {
                        "description": "Dados do álbum que será criado",
                        "name": "album",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dtos.CreateAlbumDto"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Álbum criado com sucesso",
                        "schema": {
                            "$ref": "#/definitions/entities.Album"
                        }
                    }
                }
            }
        },
        "/albums/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Álbuns"
                ],
                "summary": "Busca um álbum pelo seu ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID do álbum que será buscado",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Álbum encontrado",
                        "schema": {
                            "$ref": "#/definitions/entities.Album"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Álbuns"
                ],
                "summary": "Atualiza um álbum",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID do álbum que será atualizado",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Informações do álbum que serão atualizadas",
                        "name": "album",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dtos.UpdateAlbumDto"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Álbum atualizado com sucesso",
                        "schema": {
                            "$ref": "#/definitions/entities.Album"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "dtos.CreateAlbumDto": {
            "type": "object",
            "required": [
                "artist",
                "price",
                "title"
            ],
            "properties": {
                "artist": {
                    "type": "string",
                    "example": "John Coltran"
                },
                "price": {
                    "type": "number",
                    "example": 56.99
                },
                "title": {
                    "type": "string",
                    "minLength": 3,
                    "example": "Blue Train"
                }
            }
        },
        "dtos.UpdateAlbumDto": {
            "type": "object",
            "properties": {
                "artist": {
                    "type": "string",
                    "example": "John Coltran"
                },
                "price": {
                    "type": "number",
                    "minimum": 0,
                    "example": 56.99
                },
                "title": {
                    "type": "string",
                    "minLength": 3,
                    "example": "Blue Train"
                }
            }
        },
        "entities.Album": {
            "type": "object",
            "properties": {
                "artist": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "price": {
                    "type": "number"
                },
                "title": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "description": "Digite: Bearer {token}",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "Albums API",
	Description:      "API para gerenciamento de álbums em Clean Architecture",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
